### ISSUE TITLE
BMT Integration Tests

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-merkle#35]
Add integration tests for BMT.

This simplifies the BMT unit test suite: unit tests can test the functionality with less coupling to the context (e.g. "given", "when").

- [ ] Integration test coverage of existing BMT proof functionality

**Comment by Voxelot** [comment]
@bvrooman is this covered by the data driven test suite now?

**Comment by bvrooman** [comment]
Binary Merkle trees aren't covered by the data driven test suite. This is because calculating roots in a BMT is sufficiently simple and we can calculate the expected roots in the tests themselves, rather than feeding them in from external calculations. This [PR](https://github.com/FuelLabs/fuel-merkle/pull/36) provides an integration test suite, but it has been on the backburner for a while and needs to be updated with the latest version of master. I will make time for that this week.
