### ISSUE TITLE
Implement Merkle Sum Trees

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-merkle#5]
- Merkle Sum Tree
- Merkle Sum Verify

**Comment by Voxelot** [comment]
@bvrooman is this done?

**Comment by bvrooman** [comment]
Yes, this is done. It should be noted that we do not have a current use case for BMSTs so the definition of "done" is a bit loose. In the future, if and when we need BMSTs, we can revisit the implementation.
